### PR TITLE
fix photon modals and banners

### LINKED ISSUE #3137: Experiment tour header wrongly says that experiment is enable even if Test Pilot and the experiment are not
**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Click on any of the active experiments cards (except Send one).
3. Click the "Launch Tour" button from under the experiment logo on left column.
4. Observe the modal title displayed on the header.

**[Expected result]:**
- Experiment name is displayed on header.

**[Actual result]:**
- "<experiment_name> enabled!" message is wrongly displayed.

**[Notes]:**
- This seems to be a regression. If I remember correctly, we had the same issue in the past and it was fixed.
- The issue occurs also on stage server.

image

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #3137, #3138, #3139, #3140

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3141/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/55e2e078fcdef7341ed2a9815b6acd985dc93ae6/

File: frontend/src/app/containers/ExperimentPage/ExperimentTourDialog.js [hunk 1]
```diff
@@ -48,7 +49,10 @@ export default class ExperimentTourDialog extends React.Component {
   }
 
   renderHeaderTitle = () => {
-    const { experiment, isExperimentEnabled } = this.props;
+    const { experiment, isExperimentEnabled, isFirefox } = this.props;
+    if (!isFirefox) {
```
Comment (fzzzy) [inline frontend/src/app/containers/ExperimentPage/ExperimentTourDialog.js:53]: The user can also show the tour if they are using Firefox but don't have the experiment enabled, so this should actually check !isExperimentEnabled.
