### PR TITLE
Fix email dialog on home page, add to experiment page

### LINKED ISSUE #1447: If Test Pilot is installed from an experiment page, the "Welcome" pop-up is only displayd after navigating to "Experiments" page
Affected versions]:
- Nightly 52.0a1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to testpilot.stage.mozaws.net.
2. Click on one of the available experiments and click the "Install Test Pilot add-on" green button.
3. Follow the steps to install the add-on and observe the page behavior.
4. Click on the Firefox logo observe the page behavior.

[Expected results]:
- Step3: Test Pilot add-on is successfully installed, you are redirected to the experiment page and the "Welcome" pop-up is displayed.
- Step4: The "Experiments" page is correctly loaded without other actions. 

[Actual results]:
- Step3:  Test Pilot add-on is successfully installed, you are redirected to the experiment page, but the "Welcome" pop-up is not displayed 
- Step4: The "Experiments" page is correctly loaded but also the "Welcome" pop-up is displayed.

[Notes]:
- If the "extensions.webapi.testing" pref is set to true in order to use mozAddonManager installation, the "Welcome" pop-up is not displayed at all, no matter from what page you install it. 
- Added a screen recording with the issue: https://goo.gl/qXNSEs.

### LINKED ISSUE #1551: Bring back initial email solicitation
It appears to be missing.

### PR DESCRIPTION
**Pull request by lmorchard**
- Set first-run cookie on both old-style add-on installs and on
  new-style mozAddonManager installs.

- Add email dialog on first-run cookie to ExperimentPage

- Switch back to showEmailDialog logic with cookie in constructor,
  because the cookie was getting deleted on the first render and dialog
  state was reset with subsequent renders using hideEmailDialog logic

- Test fixes

Fixes #1551, Fixes #1447

### CODE REVIEW

File: frontend/test/app/containers/ExperimentPage-test.js [hunk 1]
```diff
@@ -232,6 +236,20 @@ describe('app/components/ExperimentPage:ExperimentDetail', () => {
         expect(subject.find('MainInstallButton')).to.have.property('length', 0);
       });
 
+      it('should show an email dialog if the first-run cookie is set', () => {
+        const getCookie = sinon.spy(name => 1);
+        const removeCookie = sinon.spy();
+        props = { ...props,  hasAddon: true, getCookie, removeCookie }
```
Comment (chuckharmston) [inline frontend/test/app/containers/ExperimentPage-test.js]: Extra space here.

**Comment by lmorchard** [comment]
Removed the space and rebased against master for good measure

File: frontend/src/app/lib/addon.js [hunk 2]
```diff
@@ -45,6 +45,8 @@ export function installAddon(requireRestart, sendToGA, eventCategory) {
     eventLabel: 'Install the Add-on'
   };
 
+  cookies.set('first-run', 'true');
```
Comment (chuckharmston) [inline frontend/src/app/lib/addon.js:48]: Maybe we should rename this? `first-run` is sort of ambiguous to the purpose here.

**Review by chuckharmston — APPROVED** [review]
Looks good here! Maybe should consider renaming the cookie to something more indicative of the purpose, but I won't block on it. Merge at will!
