### PR TITLE
Fixes #3925 [Featured experiment] Mobile platform download buttons have the different colors

### LINKED ISSUE #3925: [Featured experiment] Mobile platform download buttons wrongly have the same color
**[Affected versions]:**
- Firefox 63.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Local clone the master Test Pilot branch. 
- Perform the setup in order to run the build locally and start the server as in [quickstart ](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md) doc.
- Edit the "lockbox.yaml" file by adding the `android` one to the existing `ios` one and save the file.
- Edit the "lockbox.yaml" file by adding the `android_url:` with a link to a Google Play store app and save the file. 

**[Steps to reproduce]:**
1. Open Firefox Developer edition browser and navigate to `https://example.com:8000/ page.
2. Observe the buttons displayed for both mobile platforms.
 
**[Expected result]:**
- Both mobile platform buttons are correctly displayed and working.

**[Actual result]:**
- Both buttons have the same green color, while in the designs added on [#3672](https://github.com/mozilla/testpilot/issues/3672#issuecomment-428806072) they have different colors.

**[Notes]:**
- Here is a screenshot of the issue: 

screenshot_2018-10-30 firefox test pilot

### PR DESCRIPTION
**Pull request by KhushilMistry**
Fixes #3925 [Featured experiment] Mobile platform download buttons have the different colors

screenshot 2018-11-02 at 1 46 37 am

screenshot 2018-11-02 at 1 45 05 am

### CODE REVIEW

File: frontend/src/app/containers/ExperimentPage/ExperimentControls.js [hunk 1]
```diff
@@ -170,7 +170,7 @@ function createButtons({
         {(platforms.includes("ios")) &&
           <MobileTriggerIOSButton {...{ doShowMobileAppDialog, color: "default" }} />}
         {(platforms.includes("android")) &&
-          <MobileTriggerAndroidButton {...{ doShowMobileAppDialog, color: "default" }} />}
+          <MobileTriggerAndroidButton {...{ doShowMobileAppDialog, color: "primary" }} />}
```
Comment (meandavejustice) [inline frontend/src/app/containers/ExperimentPage/ExperimentControls.js:173]: Looks like this should stay "default" since the ios button above uses "default"

File: frontend/src/app/components/FeaturedExperiment/FeaturedButton.js [hunk 2]
```diff
@@ -169,7 +169,7 @@ export default class FeaturedButton extends Component<FeaturedButtonProps, Featu
             <React.Fragment>
               <div className="main-install__spacer"></div>
               <div className="mobile-button-wrap">
-                <MobileTriggerIOSButton doShowMobileAppDialog={this.doShowMobileAppDialog} color={"primary"} />
+                <MobileTriggerIOSButton doShowMobileAppDialog={this.doShowMobileAppDialog} color={"default"} />
```
Comment (meandavejustice) [inline frontend/src/app/components/FeaturedExperiment/FeaturedButton.js:172]: ios is getting different color than android button below

**Review by meandavejustice — CHANGES_REQUESTED** [review]

File: frontend/src/app/components/FeaturedExperiment/FeaturedButton.js (hunk 2 above)
Comment (KhushilMistry) [reply frontend/src/app/components/FeaturedExperiment/FeaturedButton.js:172]: https://github.com/mozilla/testpilot/issues/3672#issuecomment-428806072 has a suggestion to make color of both the buttons different. What should I do now ?

Comment (meandavejustice) [reply frontend/src/app/components/FeaturedExperiment/FeaturedButton.js:172]: I may be misunderstanding the goal of that issue. I'll let @youwenliang or @johngruen review this one

Comment (youwenliang) [reply frontend/src/app/components/FeaturedExperiment/FeaturedButton.js:172]: Yes I suggested using different colors for the buttons. Look good to me.
