### PR TITLE
fix hardcoded strings

### LINKED ISSUE #2775: Two strings are hardcoded in the newsletter form
“Your email here” placeholder is hardcoded:
capture d ecran 2017-08-13 a 17 27 05

“this privacy notice” is hardcoded as well:
capture d ecran 2017-08-13 a 17 26 56

Verified on production using French.

cc @flodolo

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #2775

### CODE REVIEW

File: frontend/src/app/components/MainInstallButton.js [hunk 1]
```diff
@@ -41,10 +41,10 @@ export default class MainInstallButton extends React.Component {
     const { isFirefox, isMinFirefox, isMobile, hasAddon } = this.props;
     const isInstalling = this.state.isInstalling && !hasAddon;
     const terms = <Localized id="landingLegalNoticeTermsOfUse">
-      <a href="/terms">Terms of Use</a>
+      <a href="/terms"/>
```
Comment (johngruen) [inline frontend/src/app/components/MainInstallButton.js:44]: While trying to debug this issue, i noticed that these links were not getting l10n-ized as well. Removing strings from src files seems to resolve this issue

File: frontend/src/app/components/NewsletterForm.js [hunk 2]
```diff
@@ -54,13 +54,14 @@ export default class NewsletterForm extends React.Component {
...
-        onChange={this.handleEmailChange}
-      />
+      <Localized id="newsletterFormEmailPlaceholder">
+        <input
+          type='email'
+          required
+          value={this.props.email}
+          onChange={this.handleEmailChange}
+        />
+      </Localized>
```
Comment (johngruen) [inline frontend/src/app/components/NewsletterForm.js:64]: the l10n key was already lying around, we just needed to wrap the element

File: frontend/src/app/components/MainInstallButton.js (hunk 1 above)
Comment (lmorchard) [reply frontend/src/app/components/MainInstallButton.js:44]: We need to have default strings in these elements going forward, though, per #2791. If having a string in there is causing a problem, then that might be an issue with localization that we need to fix.

Comment (johngruen) [reply frontend/src/app/components/MainInstallButton.js:44]: @lmorchard AFAIK these are the only two examples where we're passing in links like this. I'm not super familiar with fluent react, but we can ref this PR on that bug maybe?

Comment (lmorchard) [reply frontend/src/app/components/MainInstallButton.js:44]: Should probably file a new issue, since #2791 is closed. Is it that translations just don't show up at all for these elements?

Comment (lmorchard) [reply frontend/src/app/components/MainInstallButton.js:44]: Looks like #2911 is filed now. Will merge this and see if we can work things out to get the original text put back in
