### PR TITLE
Fix non rendering of legal modal for featured experiment

### LINKED ISSUE #3266: Notes Privacy modal is wrongly opened under the Tour modal after enabling Notes from "Featured Experiment" section
**[Affected versions]:**
- Firefox v57.0.4 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click the "Notes" button from under the "Enable Notes" green button.
3. Observe the Test Pilot page behavior.
4. Click the "Enable Notes" green button and follow the process.
5. Dismiss the Notes experiment tour and observe the page behavior.

**[Expected result]:**
- Step 3: Nothing happens because Notes is not enabled (bug #3231).
- Step 5: The Test Pilot "Experiments" page is correctly displayed and Notes appears as enabled on the "Featured Experiment" section.

**[Actual result]:**
- Step 3: Nothing happens because Notes is not enabled (bug #3231).
- Step 5: The Notes Privacy modal is wrongly displayed.

**[Notes]**
- The Privacy modal is opened underneath the Tour modal because you can see that the overlay accompanies the Tour modal is darker when the above steps are performed since it's doubled by the one for the Privacy. 
- This issue occurs also on Stage server.
- Here is a screen recording of the issue: https://goo.gl/XuXBZr.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #3266

### CODE REVIEW

File: frontend/src/app/components/FeaturedExperiment/FeaturedButton.js [hunk 1]
```diff
@@ -63,6 +63,19 @@ export default class FeaturedButton extends React.Component {
...
+    const { showLegalDialog } = this.state;
+    const { experiment } = this.props;
+
+    return showLegalDialog ? (<Modal wrapperClass='legal-modal'
+                              onCancel={() => this.setState({ showLegalDialog: false })}
+                              onComplete={() => this.setState({ showLegalDialog: false })}>
+                              <MeasurementSection experiment={experiment}
+                              l10nId={this.l10nId}
+                              highlightMeasurementPanel={false}></MeasurementSection>
+                              </Modal>) : null;
```
Comment (chuckharmston) [inline frontend/src/app/components/FeaturedExperiment/FeaturedButton.js]: That's a pretty needless ternary that makes the code really ugly. Can you do something like this instead?

```
if (!showLegalDialog) {
  return null;
}
return (
  <Modal ... />
);
```

**Review by chuckharmston — CHANGES_REQUESTED** [review]
Build is broken also.

**Comment by meandavejustice** [comment]
@chuckharmston changes addressed, restarted build
