### PR TITLE
fix overeager survey prompts

### LINKED ISSUE #782: asked to survey activity stream twice in two days
I installed test pilot yesterday. Within 10 minutes, it asked me to fill out a (very long) survey for activity stream.

It just asked me to fill out another survey for activity stream today.

Why is it asking me to fill out a survey for the same experiment two days in a row? That seems overly zealous.

Using Firefox dev edition 2016-05-11 on Ubuntu 16.04. I updated dev edition today--I don't remember what version I was using yesterday.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #782
- check full days difference between installDate and today instead of days within month
- kickoff survey after TEN minutes instead of FIVE
- bump version to 0.6.5

### CODE REVIEW

**Comment by ckprice** [comment]
@meandavejustice I left a comment about a [concern from Matt's team about low survey numbers at the 7-day interval](https://github.com/mozilla/testpilot/issues/782#issuecomment-223406861) that may be related to this. Let me know if you had a chance to check it out in this PR, or if we should open a new issue (but it is something that he noted was a priority).

**Comment by meandavejustice** [comment]
@ckprice This pr should address that issue.

File: addon/lib/survey.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ const querystring = require('sdk/querystring');
 const store = require('sdk/simple-storage').storage;
 
 const NUM_STARS = 5; // Number of survey stars
-const FIVE_MINUTES = 60 * 1000 * 5;
+const TEN_MINUTES = 60 * 1000 * 10;
```
Comment (lmorchard) [inline addon/lib/survey.js:19]: Nit: This should probably be named for purpose, not content - e.g. SURVEY_PROMPT_DELAY. Will probably merge anyway though
