### PR TITLE
Fixes to enable / disable flow in addon & frontend

### LINKED ISSUE #325: Enable/Disable state gets messed up after one install cycle.
https://github.com/mozilla/idea-town/pull/324#issuecomment-161717938

### PR DESCRIPTION
**Pull request by lmorchard**
- Use a one-shot listener for install-ended / uninstall-ended messages
  in frontend enable / disable buttons
- Simplify uninstall / renderUninstallSurvey handlers in frontend
- Skip addon uninstall call when frontend calls to uninstall an
  experiment that's not installed
- Ensure messages from addon to frontend happen before metrics ping
- notifyObserver -> notifyObservers typo in addon metrics ping
- Remove AddonManager listeners at unload time to prevent "can't access
  dead object" warnings due to zombie listeners

Fixes #325

### CODE REVIEW

**Comment by meandavejustice** [comment]
Would you do a `npm run package` in the addon directory?

**Comment by lmorchard** [comment]
Updated with a new addon package. It occurs to me, though that 1) we should automate that as part of the Docker build and 2) should we bump the version whenever that happens? and 3) is there anywhere we're already using this URL for addon installation? (maybe all concerns for #92)

File: idea_town/frontend/static-src/app/views/experiment-page.js [hunk 1]
```diff
@@ -185,32 +185,32 @@ export default PageView.extend({
     evt.target.style.width = width + 'px';
     evt.target.classList.add('state-change');
 
-    this.updateAddon(true, this.model);
-
-    app.on('webChannel:addon-install:install-ended', () => {
-      this.model.enabled = !this.model.enabled;
+    // TODO: Should this maybe be an event listener at a global level?
```
Comment (jaredhirsch) [inline idea_town/frontend/static-src/app/views/experiment-page.js:189]: About that TODO: I think it might make sense to abstract these install/uninstall listeners out into an Addon model, and toggle view changes by listening to `change` events on that model's attributes, something like `addonModel.on('change:isInstalled', cb)` or whatever you want to call the attrs. Dunno if you want to fold that into this PR or file a followup bug.

File: idea_town/frontend/static-src/app/views/experiment-page.js [hunk 2]
```diff
@@ -225,9 +225,7 @@ export default PageView.extend({
         { value: 'notuseful', title: 'feedbackUninstallAnswerNotUseful' },
         { value: 'other', title: 'feedbackUninstallAnswerOther' }
       ],
-      onSubmit: () => {
-        this.uninstall(this.updateAddon, this.model);
-      }
+      onSubmit: () => this.uninstall(evt)
```
Comment (jaredhirsch) [inline idea_town/frontend/static-src/app/views/experiment-page.js:229]: Should this read `(evt) => this.uninstall(evt)`?

File: addon/index.js [hunk 3]
```diff
@@ -205,6 +205,7 @@ Router.prototype.on = function(name, f) {
 };
 
 Router.prototype.send = function(name, data, addon) {
+  this.mod.port.emit('from-addon-to-web', {type: name, data: data});
```
Comment (jaredhirsch) [inline addon/index.js:210]: Is there any particular reason this line was moved to the top of the function? If it's order dependent, would be good to insert a comment above this line to that effect.

File: addon/index.js [hunk 4]
```diff
@@ -426,4 +415,21 @@ AddonManager.addInstallListener({
   onDownloadFailed: function(install) {
     app.send('addon-install:download-failed', formatInstallData(install));
   }
+};
+AddonManager.addInstallListener(installListener);
```
Comment (jaredhirsch) [inline addon/index.js:421]: Could we collect these `add*Listener` methods into some kind of addon startup method? There's some loose initialization code around lines 126-141, too. Would be great to have a single, scannable place to grok the startup sequence, and I don't think it'd be _too_ much creep for this PR.

The `unload.when` callback below looks like a great candidate to extract out into a top-level shutdown method (yay symmetry).

File: idea_town/frontend/static-src/app/views/experiment-page.js (hunk 2 above)
Comment (lmorchard) [inline idea_town/frontend/static-src/app/views/experiment-page.js:229]: No, `evt` is a reference to [the parameter to `renderUninstallSurvey`](https://github.com/mozilla/idea-town/pull/377/files#diff-9a1984ab9661edeed8d9b7bed2951b8cR216)

File: idea_town/frontend/static-src/app/views/experiment-page.js (hunk 1 above)
Comment (lmorchard) [inline idea_town/frontend/static-src/app/views/experiment-page.js:189]: That sounds like a pretty hefty PR on its own, and would rather get this fix in ASAP

File: addon/index.js (hunk 3 above)
Comment (lmorchard) [inline addon/index.js:210]: During my debugging, exceptions thrown by the metrics ping broke the frontend client too. The exception was due to a typo, but having moved this doesn't hurt things either.

File: addon/index.js (hunk 4 above)
Comment (lmorchard) [inline addon/index.js:421]: Well, this whole `index.js` is pretty much a big startup method, really. Everything is initialization

**Comment by jaredhirsch** [comment]
> Updated with a new addon package. It occurs to me, though that 1) we should automate that as part of the Docker build and 2) should we bump the version whenever that happens? and 3) is there anywhere we're already using this URL for addon installation? (maybe all concerns for #92)

It does seem weird to change the addon without at least bumping the patch number.

FWIW, I've been manually bumping the version number in the search addon, and it seems like a useful thing to have as a separate commit in git history, to help with bisecting when users start filing bugs. I'm not sure it's possible to fully automate this step, since humans need to decide whether it's a major, minor, or patch-level change.

File: addon/index.js (hunk 4 above)
Comment (lmorchard) [inline addon/index.js:421]: Might make sense to shuffle some things around - i.e. move all the functions & classes to the bottom. For example, I just now noticed the Metrics stuff got inserted between the `updatePrefs` declaration and the actual initialization of prefs. But, there's a lot going on here between prefs, metrics, toolbar button, addon/frontend message handling, and the AddonManager monitoring - that's pretty much the whole shebang in initialization :)

**Comment by jaredhirsch** [comment]
@lmorchard Looks good overall, see comments. Couple of refactoring "choose your own adventure" suggestions; I think they would be useful to do now, but if you'd rather just get this patch landed, I can run a couple of sanity checks locally and then merge; let me know.

**Comment by lmorchard** [comment]
> I'm not sure it's possible to fully automate this step, since humans need to decide whether it's a major, minor, or patch-level change.

I don't mean automating the version step so much as automating the build and rolling it into the Docker image, so we have an atomic artifact joining server / frontend / addon changes

**Comment by lmorchard** [comment]
So, some shuffling I tried actually broke things. Hope this small reorg makes things a little more sense. Also bumped the addon version.

**Comment by meandavejustice** [comment]
I just pulled this down and it's working well for me. The reorg of `index.js` looks good to me as well. I'm going to leave this to @6a68 to merge since they did most of the reviewing.

:+1:

**Comment by lmorchard** [comment]
Rebased against master just to be sure things didn't break
