### PR TITLE
fix comma in install count

### LINKED ISSUE #852: Changing user count strips out commas.
This is a good problem to have since you don't see it until user counts get above 999. Here's the bug in action: 

comma-strip

STR: 
- go to details page of any experiment
- uninstall or install
- count increments or decrements, but loses the comma that's added to the string when the view first renders

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #852

### CODE REVIEW

**Comment by meandavejustice** [comment]
@johngruen This looks great, Would you mind also adding a test in `frontend/static-src/test/views/experiment-page.js` so we don't have a regression here? We can just check that installation_count contains a `,` after rendering the view.

**Comment by johngruen** [comment]
@meandavejustice let's see if that does it. That was officially the first test I've written for Test Pilot.

File: testpilot/frontend/static-src/test/views/experiment-page.js [hunk 1]
```diff
@@ -118,6 +119,15 @@ test('updateAddon tests', t => {
   myView.updateAddon(true, myModel);
 });
 
+test('installation count gets commafied', t => {
+  t.plan(1);
+
+  const myView = new MyView({headerScroll: false, slug: 'slsk'});
+  const installCount = MyView.query('[data-hook=install-count]').innerHTML;
```
Comment (meandavejustice) [inline testpilot/frontend/static-src/test/views/experiment-page.js]: Here you are calling `MyView.query` instead of `myView.query`. Which is making our linter throw `125:9  error  "myView" is defined but never used  no-unused-vars`

also, I would use `.testContent` here instead of `.innerHTML`

File: docs/FAQs.md [hunk 2]
```diff
@@ -19,3 +19,11 @@ As this is an evolving product, this requirement may be adjusted in the future,
 - We use JavaScript to collect data to help us improve Test Pilot in accordance with our [Terms of Use](https://testpilot.firefox.com/terms) and [Privacy Notice](https://testpilot.firefox.com/privacy).
 
 Since Test Pilot is an open source project, you can see all of the cool ways we use JavaScript by [examining our code](https://github.com/mozilla/testpilot/).
+
+### I tried to enable an experiment, but it didn't work. What went wrong?
+
+Well it count be a number of things. Test Pilot experiments are just add-ons, so if you've done anything to your copy of Firefox to change the way add-ons install, that...
```
Comment (pdehaan) [inline docs/FAQs.md]: typo: "count" > "could".

Also, not sure if the lorem ipsum is useful below or if we want to remove this FAQ until we have a fuller answer.

File: locales/en-US/app.l20n [hunk 3]
```diff
@@ -96,6 +96,8 @@
 <userCountContainer "There are <span class=\"bold\">{{installation_count}}</span> people trying {{title}} right now!">
 <highlightPrivacy "Your privacy">
 
+<timeoutErrorText "<span data-hook=\"title\"></span> could not be enabled.">
```
Comment (pdehaan) [inline locales/en-US/app.l20n]: Can this be `"{{title}} could not be enabled."`?

**Comment by pdehaan** [comment]
Circle-CI says:

```
  not ok 30 Error: Query cannot be performed as `this.el` is not defined. Ensure that the view has been rendered.

⨯ installation count gets commafied    ---
      operator: error
      expected: |-
        undefined
      actual: |-
        [Error: Query cannot be performed as this.el is not defined. Ensure that the view has been rendered.]
      at: Test.assert (http://localhost:41300/__testling?show=true:35014:17)
      stack: |-
        Error: Query cannot be performed as this.el is not defined. Ensure that the view has been rendered.
            at assign.query (http://localhost:41300/__testling?show=true:25488:19)
            at http://localhost:41300/__testling?show=true:38538:29
            at http://localhost:41300/__testling?show=true:34324:12
            at http://localhost:41300/__testling?show=true:34321:12
    ...
```

File: locales/en-US/app.l20n (hunk 3 above)
Comment (johngruen) [inline locales/en-US/app.l20n]: ahh, i got my PRs crossed...crap

**Comment by pdehaan** [comment]
Circle-CI says:

```
# installation count gets commafied

  not ok 30 (unnamed assert)
⨯ installation count gets commafied    ---
      operator: ok
      expected: true
      actual:   false
      at: Test.assert (http://localhost:55104/__testling?show=true:35014:17)
    ...
```

Since we're setting the experiment `installation_count` to `123456` earlier, not sure if we should just verify that the `installCount` is displayed as the string `"123,456"` versus just checking for a comma. At the very least, it may give us some more interesting failure messages instead of just a Boolean expected/actual.
