### PR TITLE
Fixes #2809: Convert JSX in pages.js to React components

### LINKED ISSUE #2809: Pages.js could make better use of react components
[`frontend/tasks/pages.js`](https://github.com/mozilla/testpilot/blob/master/frontend/tasks/pages.js) has a bunch of JSX that could be converted to components, specifically, there's a reference to `layout-wrapper` and `copter` classes that could be component-ized.

### LINKED ISSUE #3616: Wrong footer displayed for "Privacy", "Terms" and "About" pages
**[Affected versions]:**
- Firefox 60.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to `https://testpilot.firefox.com page.
2. Scroll down to the new footer section.
3. Click on the `Privacy` or `Terms` links from bottom left or `About us` link from "About" section.
4. Scroll down to the page footer if needed and observe it.

**[Expected result]:**
- The same footer as on Homepage is correctly displayed on all 3 mentioned pages

**[Actual result]:**
- A footer that resembles to the old one is wrongly displayed.

terms wrong footer

### PR DESCRIPTION
**Pull request by kgeorgiou**
Fixes #2809 
New components:
- NoScript 
    - Contains the `<noscript>...</noscript>` section
    - Moved the English translation of "Test Pilot requires JavaScript. Sorry about that." to the top.
- Head
    - Contains the `<head>` metadata

Markdown pages:
- Replaced container div with `LayoutWrapper`
- Replaced the `<footer>...</footer>` section with the `Footer` component. I believe this closes #3616.

### CODE REVIEW

File: frontend/tasks/pages.js [hunk 1]
```diff
@@ -200,100 +202,25 @@ function generateStaticPage(prepareForClient, pageName, pageParam, component, {
...
-    { prepareForClient ? <script src="/static/app/vendor.js"></script> : null }
+    <NoScript />
+    {prepareForClient ? <script src="/static/app/vendor.js"></script> : null}
   </div>;
 
   return makeStaticString(prepareForClient, pageName, pageParam, headComponent, bodyComponent, component);
 }
 
 function generateStaticPageFromMarkdown(pageName, pageParam, markdown, params) {
+  // TODO: Reuse Header component
```
Comment (kgeorgiou) [inline frontend/tasks/pages.js:223]: For now, the Header component can't be used here because it contains a Link that can only exist inside a Router.

File: frontend/tasks/pages.js [hunk 2]
```diff
@@ -304,27 +231,12 @@ function generateStaticPageFromMarkdown(pageName, pageParam, markdown, params) {
         <a className="blog-link" href="https://medium.com/firefox-test-pilot" target="_blank" rel="noopener noreferrer">Blog</a>
       </div>
     </header>
-    <div className="layout-wrapper static-page-content">
-      <ReactMarkdown source={ markdown } />
-    </div>
 
-    <footer id="main-footer">
```
Comment (lmorchard) [inline frontend/tasks/pages.js:311]: Huh, I wonder if there's a reason why we had this markup here for the footer rather than just reuse the `<Footer>` component like you've done here? They're slightly different, but I wonder if that's just because we've neglected this file while updating the Footer component - in which case, hooray for DRYer code!

Comment (lmorchard) [reply frontend/tasks/pages.js:311]: Oh hey, yeah, this indeed looks like a fix for #3616

Comment (lmorchard) [reply frontend/tasks/pages.js:311]: Also looks like a fix for #3626

**Comment by lmorchard** [comment]
Looks good to me and seems to take care of 3 issues in one go! Thanks!
