### PR TITLE
changed RowCard links again

### LINKED ISSUE #3467: Experiments cards have lost their URL's which makes them impossible to be opened in separate tabs
**[Affected versions]:**
- Firefox Nightly 61.0a1 

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 3 prefs have been set or added on a new profile: "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Hover over the available experiments cards and right click one of them.
3. Choose the "Open Link in New Tab" option from context menu.

**[Expected result]:**
- The experiment details page is opened in a new tab.

**[Actual result]:**
- There are no link options in the displayed context menu.

context menu

### PR DESCRIPTION
**Pull request by dannycoates**
fixes #3467

use the `<object>` hack to get around nested `a` elements

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3472/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/a4c0d9c911546db5bd3fb40230a909dbbd1f8cb6/

File: frontend/src/app/components/ExperimentRowCard/index.js [hunk 1]
```diff
@@ -104,15 +104,15 @@ export class ExperimentRowCard extends React.Component {
     const { title, survey_url } = experiment;
     const surveyURL = buildSurveyURL("givefeedback", title, installed, clientUUID, survey_url);
     return (
-      <div>
+      <object>
```
Comment (lmorchard) [inline frontend/src/app/components/ExperimentRowCard/index.js]: Seems to work, but what's with the `<object>` hack? What's it do, etc?

Comment (lmorchard) [inline frontend/src/app/components/ExperimentRowCard/index.js:107]: Seems to work, but what's with the `<object>` hack? What's it do, etc?

**Review by lmorchard — APPROVED** [review]
Works for me, but the hack gave me a headscratch

File: frontend/src/app/components/ExperimentRowCard/index.js (hunk 1 above)
Comment (dannycoates) [reply frontend/src/app/components/ExperimentRowCard/index.js:107]: http://kizu.ru/en/fun/nested-links/

The original issue came from #3429 where react complained about nested links, and the react-router PR broke the feedback button.

Comment (lmorchard) [reply frontend/src/app/components/ExperimentRowCard/index.js:107]: FWIW, might help to at least have a short comment in there pointing at that blog post because it's a weird hack. (Like, we *might* run into the caveat at the bottom as an issue in the future - "Fire­fox’ Flash­block plu­gin re­moves “bro­ken ob­jects”, and it treats at­tribut­e­less <ob­ject> as such")
