### PR TITLE
fix sms and email ids per marketing suggestion

### LINKED ISSUE #3677: Pass message ids to basket for sms
format should be `txp-${experiment.slug}`

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #3677

Note, #3694 means that this breaks the basket calls until we get working ids

### CODE REVIEW

File: frontend/src/app/components/MobileDialog/index.js [hunk 1]
```diff
@@ -238,7 +238,7 @@ export default class MobileDialog extends React.Component {
 
     const { allowSMS, recipient, country } = this.state;
     const { sendToGA, getWindowLocation, fromFeatured, experiment } = this.props;
-    const basketMsgId = this.props.experiment.basket_msg_id;
+    const basketMsgId = `txp-${this.props.experiment.slug}`;
```
Comment (johngruen) [inline frontend/src/app/components/MobileDialog/index.js:241]: This is just copied from @meandavejustice PR

File: frontend/src/app/components/MobileDialog/index.js [hunk 2]
```diff
@@ -276,7 +276,7 @@ export default class MobileDialog extends React.Component {
       dimension13: fromFeatured ? "Featured Experiment" : "Experiment Detail"
     });
 
-    return subscribeToBasket(recipient, source).then(response => {
+    return subscribeToBasket(recipient, source, basketMsgId).then(response => {
```
Comment (johngruen) [inline frontend/src/app/components/MobileDialog/index.js]: The intent was to pass an optional param in to become the newsletter value and otherwise default to test pilot

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3693/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/1ca5ba8651df33ca363abb1ef14e9834c940ccd5/

File: frontend/src/app/lib/utils.js [hunk 3]
```diff
@@ -12,7 +12,7 @@ export function subscribeToBasket(email, source) {
   return fetch(basketUrl, {
     method: "POST",
     headers: { "Content-Type": "application/x-www-form-urlencoded" },
-    body: `newsletters=test-pilot&email=${encodeURIComponent(email)}&source_url=${encodeURIComponent(sourceUrl)}`
+    body: `newsletters=PIZZA&email=${encodeURIComponent(email)}&source_url=${encodeURIComponent(sourceUrl)}`
```
Comment (johngruen) [inline frontend/src/app/lib/utils.js]: but changing the value to anything but

**Comment by johngruen** [comment]
Fixes #3677

Note, #3694 means that this breaks the basket calls until we get working ids

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3693/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/f7bab2d280ffc2f918b5281b6cae7c0112e91b41/
