### PR TITLE
[fixes #711] Remove window.open

### LINKED ISSUE #711: Survey popup blocked w/ Nightly
Found in https://testpilot.stage.mozaws.net/__version__ (ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5):

``` json
{ "build": "https://circleci.com/gh/mozilla/testpilot/325",
  "commit": "ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-05-04"}
```

---
### Steps to reproduce:
1. Go to https://testpilot.stage.mozaws.net/ and sign in using Nightly (possibly relevant).
2. Enable and disable an experiment.
3. After disabling the add-on/experiment, click the [Take a quick survey] button.
### Actual results:

> Nightly prevented this site from opening a pop-up window.

firefox_test_pilot_-_tab_center

I also noticed that my Developer Tools console said;

> TypeError: `window.open(...)` is `null`

(presumably because of the blocked pop-up.
### Expected results:

I should be able to see the survey.
Currently I'm in a state where the add-on/experiment is now disabled and I'm unable to provide feedback.
I am now faced with two equally unpleasant options:
1. Click [Enable Tab Center] button, then click [Give Feedback] button to give feedback. (This didn't work and now Firefox says "Nightly prevented this site from opening 2 pop-ip windows.")
2. Click [Enable Tab Center] button, then click [Disable Activity Stream] add-on. (This didn't work because it's the same steps as the original steps to reproduce.)
3. Disable pop-up blocker and try option 1 or 2 above.

The mostly likely solution is that I'm impossibly lazy, and won't run through the 2-3 steps to try and give feedback now that the popup was disabled.

### PR DESCRIPTION
**Pull request by ckprice**
- update `sendToGA` to not handle opening links in new tab
- update all external links to use normal `_blank`

Fixes #711

### CODE REVIEW

**Comment by ckprice** [comment]
@lmorchard @meandavejustice r? Not super confident on how I handled [rendering the experiment survey URLs](https://github.com/mozilla/testpilot/pull/735/commits/f90354eac591ab998369eea52ed42520a5478857#diff-59f5e52c87ff47eddc3834d7e5293990R179). Open to suggestions.

File: testpilot/frontend/static-src/app/views/disable-dialog-view.js [hunk 1]
```diff
@@ -48,15 +48,12 @@ export default BaseView.extend({
...
-  submit(ev) {
-    ev.preventDefault();
+  submit() {
     this.animateRemove();
     app.sendToGA('event', {
       eventCategory: 'ExperimentDetailsPage Interactions',
       eventAction: 'button click',
-      eventLabel: 'exit survey disabled',
-      newTab: true,
-      outboundURL: ev.target.getAttribute('href')
```
Comment (pdehaan) [inline testpilot/frontend/static-src/app/views/disable-dialog-view.js:59]: Did we want to lose the `outboundURL` here?

**Comment by lmorchard** [comment]
Seems to work fine for me, r+ from me unless there's something in particular you're worried about that I'm missing

**Comment by ckprice** [comment]
> Seems to work fine for me, r+ from me unless there's something in particular you're worried about that I'm missing

Nope! Just wanted to make sure this was a good way to send things to the template. Feel free to merge if ok, thanks!

File: testpilot/frontend/static-src/app/views/disable-dialog-view.js (hunk 1 above)
Comment (ckprice) [inline testpilot/frontend/static-src/app/views/disable-dialog-view.js:59]: We do, and I think it is?

Comment (lmorchard) [inline testpilot/frontend/static-src/app/views/disable-dialog-view.js:59]: Yeah, [the "Take a quick survey" link](https://github.com/mozilla/testpilot/pull/735/files#diff-8c337e6daa565ff7880666fe0c65a403R20) now should natively open in a new window/tab since [the `ev.preventDefault()` was removed](https://github.com/mozilla/testpilot/pull/735/files#diff-8c337e6daa565ff7880666fe0c65a403L52) and `target="_blank"` was added. Meanwhile this `sendToGA` call happens passively and doesn't attempt to use `window.open`, which was causing our pop-up blocker issue.
