### PR TITLE
fix ios icon in modal

### LINKED ISSUE #3651: The "Send App Link to Device" modal wrongly displays the iOS App Store black button instead of white one
**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to `https://testpilot.dev.mozaws.net page.
2. Scroll down to the experiments list and click on "Dev Example" card.
3. Observe the "Download on the App Store" button on the experiment control area.
4. Click on the "Send App Link to Device" blue button from the experiment control area.
5. Observe the "Download on the App Store" button displayed on the modal.

**[Expected result]:**
- Bot the App Store buttons have the same aspect on the experiment details page and modal.

**[Actual result]:**
- The button on the experiments details is white with black icon and text, while the modal wrongly displays a black button with white icon and text.

**[Additional notes]:**
- Here is a screenshot of the issue:

image

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #3651

### CODE REVIEW

File: frontend/src/app/containers/ExperimentPage/MobileDialog.js [hunk 1]
```diff
@@ -78,7 +78,7 @@ export default class MobileDialog extends React.Component {
     const headerMessage = ios_url ? (<LocalizedHtml id="mobileDialogMessageIOS" $title={title}>
       <p>Download <b>{title}</b> from the iOS App Store.</p></LocalizedHtml>) : (<LocalizedHtml id="mobileDialogMessageAndroid" $title={title}><p>Download <b>{title}</b> from the Google Play Store.</p></LocalizedHtml>);
 
-    const headerImg = ios_url ? (<a href={ios_url} target="_blank"><img className="mobile-header-img" src="/static/images/ios.svg"/></a>) : (<a href={android_url} target="_blank"><img className="mobile-header-img" src="/static/images/google-play.png"/></a>);
+    const headerImg = ios_url ? (<a href={ios_url} target="_blank"><img className="mobile-header-img" src="/static/images/ios-light.svg"/></a>) : (<a href={android_url} target="_blank"><img className="mobile-header-img" src="/static/images/google-play.png"/></a>);
```
Comment (lmorchard) [inline frontend/src/app/containers/ExperimentPage/MobileDialog.js]: We might want to hold off on this until #3647 is merged, because it moves this MobileDialog stuff into a separate component. That, or we merge this and that other PR has to be tweaked

**Comment by devinreams** [comment]
OK #3647 was merged and a rebase here (with a fancy 3-way merge) magically got this in the right spot. Ready to rock? 👍 👎

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3654/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/a50d12a7776c63032cdbec0169daae590465fc54/

**Comment by lmorchard** [comment]
:shipit:
