### PR TITLE
Fix inconsistency in app.me.installed

### LINKED ISSUE #742: audit app.me.installed data
https://github.com/mozilla/testpilot/pull/726#issuecomment-217892254

`/api/me` installed key returns addon objects in an array
`sync-installed` event from addon returns objects in the shape of:

``` json
"univeral-search@mozilla.com" {
  "some-data": "for the addon"
}
```

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #742
- users/serializers Me now returns installed in format:
  {addon_id: {addon: data}}
- fix consumption of me.installed data in addon/index.js
- bump addon package version to 0.6.4
- update experiments/tests to match new data shape
- fix default obj for installed in me.js model
- catch and log occasional error in me.js when sync-installed fails
- update experiment-page.js tests for installed shape update
- update users view and tests to send data correctly
- reformate line in experiments/serializers.py for pep8

I think this will take care of the white screen of death issue as well. refs #719 
There was an issue where `sync-installed` would timeout/fail and we did nothing with the error except reject. Which in turn threw an error in the `async.all` call in main.js, essentially sabotaging our whole plot to ship new features.

### CODE REVIEW

File: testpilot/frontend/static-src/app/models/me.js [hunk 1]
```diff
@@ -46,6 +46,8 @@ export default Model.extend({
         .then(result => {
           this.clientUUID = result.clientUUID;
           this.installed = result.installed;
+        }).catch((err) => {
+          console.error('sync-installed failed', err);
```
Comment (pdehaan) [inline testpilot/frontend/static-src/app/models/me.js]:
```
testpilot/frontend/static-src/app/models/me.js
  50:11  warning  Unexpected console statement  no-console

✖ 1 problem (0 errors, 1 warning)
```

Not sure if we want to just inline disable that rule for the `console.error()` (ie: `// eslint-disable-line no-console`), or maybe send the error event through GA or some other monitoring service. Or whatever.

File: testpilot/experiments/tests.py [hunk 2]
```diff
@@ -288,7 +288,8 @@ def test_features_list(self):
     def test_me_list(self):
         """/api/me installation listing should include feature flags"""
         result = self.jsonGet('me-list')
-        self.assertEqual(result['installed'][0]['features'], {
+        print(list(result['installed'].values()))
```
Comment (lmorchard) [inline testpilot/experiments/tests.py]: Nit: Should probably take out this print statement, though it's in a test and won't affect the server

File: testpilot/users/tests.py [hunk 3]
```diff
@@ -277,19 +277,23 @@ def test_get_logged_in(self):
         resp = self.client.get(self.url)
         result_data = json.loads(str(resp.content, 'utf-8'))
 
+        print(result_data)
```
Comment (lmorchard) [inline testpilot/users/tests.py]: Same for this print statement

File: testpilot/frontend/static-src/app/models/me.js (hunk 1 above)
Comment (lmorchard) [inline testpilot/frontend/static-src/app/models/me.js]: Might be worth leaving the warning there as a reminder to circle back if/when we have a proper error reporting thing like Sentry for the front end. We have a few places in the code where a `.catch(err =>` just ends up in a ¯\_(ツ)_/¯  `console.error` line

File: addon/index.js [hunk 4]
```diff
@@ -346,9 +346,13 @@ function updateExperiments() {
 function syncAllAddonInstallations(serverInstalled) {
   const availableIDs = Object.keys(store.availableExperiments);
   const clientIDs = Object.keys(store.installedAddons);
-  const serverIDs = serverInstalled
-    .filter(item => item.client_id === store.clientUUID)
-    .map(item => item.addon_id);
+  const serverIDs = [];
```
Comment (lmorchard) [inline addon/index.js:352]: Oof, you know something just occurred to me: After this makes it to prod, we will have a period where folks are running the previous add-on against the site until their Firefox looks for an update. Will the API change break the old version of the add-on in a nasty way? If so, we may need to consider [versioning the API](https://github.com/mozilla/testpilot/issues/53).

Comment (lmorchard) [inline addon/index.js:352]: Something we could do short of versioning the API for now: That `serverInstalled` data [comes from the web frontend](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/models/me.js#L45) in the `sync-installed` message - the add-on doesn't hit the API for that data itself.

So, on the frontend, we could convert that installation object into the array the existing add-on version expects, and hold off on the add-on change until/unless we get a versioned API

Comment (meandavejustice) [inline addon/index.js:352]: @lmorchard How long would this period be before users would be updated to the new addon?

Comment (lmorchard) [inline addon/index.js:352]: I'd guess 24 to 48 hours for addon updates, assuming everyone's Firefoxes are running at some point during that period to wake up & check

Comment (meandavejustice) [inline addon/index.js:352]: How involved is it currently to create a versioned api? (time estimate)

Comment (lmorchard) [inline addon/index.js:352]: Not really sure, I need to dig into DRF and see what that entails. Could be simple, but need to spend some hours figuring that out. (Issue #53) That's why I suggest doing a tweak on the frontend for now to convert to the old format for the add-on's sake until that's worked out.

**Comment by lmorchard** [comment]
Okay, so after some poking, I realized that [enabling versioning on the API is pretty easy](https://github.com/mozilla/testpilot/pull/933). But, in attempting to use that, I realized the problem is more complicated: 

The _frontend_ makes the initial request to the API for `/api/me`, not the add-on. But, the frontend gets deployed along with the API, so there's no version mismatch there. It's just the add-on that can lag behind the rest of the site.

The add-on gets a message from the frontend with that data. That means, the _frontend_ needs to know the add-on version - so that it can branch send the expected format. (i.e. an array for old add-on versions, an object for future versions)

So, along with enabling API versioning, I also made a tweak to the add-on in [that PR](https://github.com/mozilla/testpilot/pull/933) to expose the add-on version as `window.navigator.testpilotAddonVersion`.

With that, you can do something like this [in `app/models/me.js`](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/models/me.js#L45):

```
let installedData;
if (!window.navigator.testpilotAddonVersion) {
  // Previous add-ons didn't expose version info, so assume old API data
  installedData = Object.values(userData.installed); // Maybe Object.values needs a polyfill?
} else {
  // TODO: Need a semver matching check here someday, but for now we can assume
  // just the presence of a version means we're in the future.
  installedData = userData.installed;
}

return app.waitForMessage('sync-installed', installedData)
.then(result => {
  this.clientUUID = result.clientUUID;
  this.installed = result.installed;
});
```

**Comment by meandavejustice** [comment]
@lmorchard This is perfect. Thanks for figuring this out. I'll look over your versioning pr and get this updated.

File: testpilot/frontend/static-src/app/models/me.js [hunk 5]
```diff
@@ -1,6 +1,8 @@
 import app from 'ampersand-app';
 import cookies from 'js-cookie';
 import Model from 'ampersand-model';
+// Object.values only has support in ff 47 and ^
+import values from 'object.values';
```
Comment (lmorchard) [inline testpilot/frontend/static-src/app/models/me.js]: Hmm, something missing from package.json? Might be worth doing something like:

```
installedData = [];
for (let k in userData.installed) {
  installedData.push(userData.installed[k]);
}
```

Comment (meandavejustice) [inline testpilot/frontend/static-src/app/models/me.js]: I had some weird issues on my rebase, I'll replace with this^

**Comment by lmorchard** [comment]
Tests are passing, things look good on a skim-through, going to give it a run through and probably merge very soon
