### PR TITLE
fix margins and privacy on small details pages

### LINKED ISSUE #1282: Add padding back to middle breakpoint on details page
screen shot 2016-08-25 at 12 54 41 pm

@clouserw this needs to land before we tag

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #1282 

@chuckharmston i also added the ability to show the install and show privacy on the installed details page

### CODE REVIEW

File: testpilot/frontend/static-src/app/templates/experiment-page.js [hunk 1]
```diff
@@ -91,6 +91,13 @@ export default `
                 </section>
               </div>
               <div class="details-list"></div>
+              <div data-hook="active-user">
```
Comment (johngruen) [inline testpilot/frontend/static-src/app/templates/experiment-page.js:94]: I realize duping this hook is a hack, but it will appease legal and handle the edge case

File: testpilot/frontend/static-src/app/views/experiment-page.js [hunk 2]
```diff
@@ -317,6 +317,7 @@ export default PageView.extend({
     function cleanup() {
       evt.target.disabled = false;
       evt.target.classList.remove('state-change');
+      evt.target.style.width = '';
```
Comment (johngruen) [inline testpilot/frontend/static-src/app/views/experiment-page.js:320]: added these to clear the button width after install/uninstall otherwise the calculated width for the state change persists and you get funky button sizes

File: testpilot/frontend/static-src/styles/modules/_experiment-details.scss [hunk 3]
```diff
@@ -165,11 +232,11 @@
 }
 
 .eol-block {
-  padding: 10px !important;
-  border-radius: 3px;
   background: $eol-light-orange;
   border: 1px solid $eol-orange;
+  border-radius: 3px;
   margin-bottom: 20px;
+  padding: 10px !important;
```
Comment (johngruen) [inline testpilot/frontend/static-src/styles/modules/_experiment-details.scss:239]: @pdehaan this is left over from @dannycoates...if you want to get on somebody's case about using important, take it up with him :)

File: testpilot/frontend/static-src/styles/_layout.scss [hunk 4]
```diff
@@ -85,3 +85,13 @@
 .overflow-hidden {
   overflow: hidden;
 }
+
+.show-on-small {
+  @include respond-to('not-small') {
+    display: none;
+  }
+
+  @include respond-to('small') {
```
Comment (chuckharmston) [inline testpilot/frontend/static-src/styles/_layout.scss]: No need for this media query. Just have it be block by default, and override when not-small.

Comment (chuckharmston) [inline testpilot/frontend/static-src/styles/_layout.scss]: Careful where you use this, though. We have a bunch of elements that want to be `flex` and not `block`.

Comment (johngruen) [reply testpilot/frontend/static-src/styles/_layout.scss]: yeah, i might change this

Comment (chuckharmston) [inline testpilot/frontend/static-src/styles/_layout.scss]: It might make more sense as a mixin, now that I think about it. Single param, default `block`, can be overriden when appropriate.

**Comment by chuckharmston** [comment]
Seems fine. I'll hold off on merging myself in case you want to address the nit above; feel free to ship whenever, @johngruen.

**Comment by johngruen** [comment]
@chuckharmston good call on the mixins! be good to go now
