### PR TITLE
fixed daily ping format

### LINKED ISSUE #2206: Daily telemetry ping is misformatted
The daily telemetry ping is an integer in the event field (which breaks our pipeline schema expectations of `event` being a string):
`"events":[{"timestamp":851080,"event":0,"object":"daily"}]`

Looks like the [parameters might be swapped](https://github.com/mozilla/testpilot/blob/e16941fdf687239d41a1a4e82822a5ffaa2d3214/addon/src/main.js#L82-L85), but also, the [telemetry doc for testpilot](https://github.com/mozilla/testpilot/blob/df90f3b05c4a90ee73ee4a92d1625fa99e77a2bb/docs/metrics/telemetry.md#testpilot-summary-ping) specifies that the datatypes for both `event` and `object` should be strings.

### PR DESCRIPTION
**Pull request by dannycoates**
fixes #2206

### CODE REVIEW

File: addon/src/lib/Telemetry.js [hunk 1]
```diff
@@ -49,7 +49,7 @@ export default class Telemetry {
     }
   }
 
-  ping(object: any, event: any, time?: number) {
+  ping(object: string, event: string, time?: number) {
```
Comment (fzzzy) [inline addon/src/lib/Telemetry.js:52]: flow === 👍
